### ISSUE TITLE
React should be a peerDependency, not a dependency of react-nl2br

### ISSUE THREAD

**Issue by sentience** [yosuke-furukawa/react-nl2br#13]
We noticed that we were getting a second copy of React included in our application bundle, and this was due to react-nl2br declaring React as a dependency.

Since the expectation would be that the host project would be using React, and you want react-nl2br to use the host project's copy of React, react-nl2br should list React as a `peerDependency` in package.json, not as a `dependency`.

**Comment by lorenzos** [comment]
Please, release it on NPM!

**Comment by yosuke-furukawa** [comment]
oops, thank you!

**Comment by yosuke-furukawa** [comment]
released v0.3.0

**Comment by lorenzos** [comment]
Thank you!
