### ISSUE TITLE
Can you please add an open source license, MIT maybe?

### ISSUE THREAD

**Issue by claude** [yosuke-furukawa/react-nl2br#25]
In order to use this, we need there to be an open source license. I'm happy to submit a PR adding it for you if you are OK with MIT.

**Comment by yosuke-furukawa** [comment]
Yes MIT LICENSE. I uploaded LICENSE.md. thanks.

**Comment by claude** [comment]
Thanks!

**Comment by megapro17** [comment]
claude in 2020 🫪

**Comment by muneebIsLOL** [comment]
claude account was acquired 🫪
