### ISSUE TITLE
Cannot install v1.0.0 because of wrong dependency version constraint

### ISSUE THREAD

**Issue by ehmPlankje** [yosuke-furukawa/react-nl2br#40]
The package.json requires `@types/react@^16.14.0`. However, the latest version of `@types/react` is `16.9.56`.

The numbering of `@types/react` does not run parallel to `react`.

**Comment by yosuke-furukawa** [comment]
Thank you for reporting, I will fix it.

**Comment by yosuke-furukawa** [comment]
released v1.0.1
